version: "3.8"

services:
  web:
    build: .
    image: apptrix-manager-static:latest
    container_name: apptrix-manager
    ports:
      - "1020:80"     # ajuste se quiser outra porta
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
